# Generated by Django 4.1.4 on 2023-06-29 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autorization', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
