# Generated by Django 4.1.4 on 2023-06-30 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autorization', '0002_delete_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
